name: Docker Publish Release

on:
  release:
    types: [published, edited]

  # Can be triggered manually
  workflow_dispatch:
    inputs:
      release:
        required: true
        description: The version to generate
      git-ref:
        required: true
        description: The git reference to checkout prior to running the docker build
      force-latest:
        required: true
        type: choice
        default: 'false'
        description: Whether to force a latest tag on the release
        options:
          - true
          - false
jobs:
  docker-release:
    permissions:
      contents: read
      packages: write
      attestations: write
    name: docker-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_preset: ["dev", "lean", "py310", "websocket", "dockerize"]
      fail-fast: false
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        env:
          DOCKERHUB_USER: ${{ github.actor }}
          DOCKERHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE="${{ github.event.release.tag_name }}"
          FORCE_LATEST=""
          EVENT="${{github.event_name}}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # in the case of a manually-triggered run, read release from input
            RELEASE="${{ github.event.inputs.release }}"
            if [ "${{ github.event.inputs.force-latest }}" = "true" ]; then
              FORCE_LATEST="--force-latest"
            fi
            # build_docker.py may not exist on that SHA, let's switcharoo to /tmp
            cp ./scripts/build_docker.py /tmp
            git checkout "${{ github.event.inputs.git-ref }}"
            cp /tmp/build_docker.py scripts/
            EVENT="release"
          fi
          pip install click
          # Make a multi-platform image
          ./scripts/build_docker.py \
            ${{ matrix.build_preset }} \
            "$EVENT" \
            --build_context_ref "$RELEASE" $FORCE_LATEST \
            --platform "linux/arm64" \
            --platform "linux/amd64"
